import math

#sizes
SCREEN_WIDTH, SCREEN_HEIGHT = 1500, 780
WORLD_WIDTH, WORLD_HEIGHT = 6000, 20000

MINIMAP_X_SIZE = 200
MINIMAP_Y_SIZE = 770
TILE_SIZE = 150
MINIMAP_X = SCREEN_WIDTH - MINIMAP_X_SIZE
MINIMAP_Y = SCREEN_HEIGHT - MINIMAP_Y_SIZE - 7

SCALE_X = MINIMAP_X_SIZE / WORLD_WIDTH
SCALE_Y = MINIMAP_Y_SIZE / WORLD_HEIGHT

ZONE = math.gcd(WORLD_WIDTH, WORLD_HEIGHT)
CANT_ZONE = int((WORLD_WIDTH / ZONE) * (WORLD_HEIGHT / ZONE))

ALL_SPRITES = []

#colors
C_WHITE = (255, 255, 255)
C_GREEN = (0, 255, 110)
C_BLUE = (0, 0, 220)
C_BROWN = (163, 69, 19)